<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Kanji\Mappings\Kanjidic2Extension_Kanjidic2_Converter.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
		<PackageReference Include="FastCache.Cached" Version="1.8.1" />
		<PackageReference Include="Google.Protobuf" Version="3.26.1" />
		<PackageReference Include="Grpc.Net.Client" Version="2.62.0" />
		<PackageReference Include="Grpc.Tools" Version="2.62.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.32.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Japanese.CachedRepository\Japanese.CachedRepository.csproj" />
		<ProjectReference Include="..\Japanese.Kanjidic2\Japanese.Kanjidic2.csproj" />
		<ProjectReference Include="..\Japanese.Repositories\Japanese.Repositories.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Dictionary\Consts\" />
		<Folder Include="Dictionary\Mappings\" />
		<Folder Include="Dictionary\Commands\" />
		<Folder Include="Dictionary\Queries\" />
		<Folder Include="Kana\Commands\" />
	</ItemGroup>
</Project>
