<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5b6bbcb5-d7c3-4310-9fb5-8905eb0f2ceb</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Admin\Data\**" />
    <Compile Remove="Areas\Admin\Models\**" />
    <Compile Remove="Areas\Admin\Views\**" />
    <Compile Remove="Areas\Public\Data\**" />
    <Compile Remove="Areas\Public\Models\**" />
    <Compile Remove="Areas\Public\Views\**" />
    <Content Remove="Areas\Admin\Data\**" />
    <Content Remove="Areas\Admin\Models\**" />
    <Content Remove="Areas\Admin\Views\**" />
    <Content Remove="Areas\Public\Data\**" />
    <Content Remove="Areas\Public\Models\**" />
    <Content Remove="Areas\Public\Views\**" />
    <EmbeddedResource Remove="Areas\Admin\Data\**" />
    <EmbeddedResource Remove="Areas\Admin\Models\**" />
    <EmbeddedResource Remove="Areas\Admin\Views\**" />
    <EmbeddedResource Remove="Areas\Public\Data\**" />
    <EmbeddedResource Remove="Areas\Public\Models\**" />
    <EmbeddedResource Remove="Areas\Public\Views\**" />
    <None Remove="Areas\Admin\Data\**" />
    <None Remove="Areas\Admin\Models\**" />
    <None Remove="Areas\Admin\Views\**" />
    <None Remove="Areas\Public\Data\**" />
    <None Remove="Areas\Public\Models\**" />
    <None Remove="Areas\Public\Views\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\CommonWordController.cs" />
    <Compile Remove="Controllers\HiraganaController.cs" />
    <Compile Remove="Controllers\KanjiLevelController.cs" />
    <Compile Remove="Controllers\KanjiTypeController.cs" />
    <Compile Remove="Controllers\KatakanaController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Japanese.Services\Japanese.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
