<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Implements\**" />
    <EmbeddedResource Remove="Implements\**" />
    <None Remove="Implements\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Implements\JapaneseRepository.cs" />
    <Compile Include="Implements\KanaRepository.cs" />
    <Compile Include="Implements\KanjiComponentRepository.cs" />
    <Compile Include="Implements\Kanjidic2Repository.cs" />
    <Compile Include="Implements\KanjiRadicalRepository.cs" />
    <Compile Include="Implements\Kanjidic2ExtensionRepository.cs" />
    <Compile Include="Implements\SentenceRepository.cs" />
    <Compile Include="Implements\JMdictRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Japanese.Core\Japanese.Core.csproj" />
    <ProjectReference Include="..\Japanese.LanguageCore\Japanese.LanguageCore.csproj" />
    <ProjectReference Include="..\Japanese.Models\Japanese.Models.csproj" />
  </ItemGroup>

</Project>
