<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.Identity.Cognito" Version="3.0.1" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.200.10" />
    <PackageReference Include="AWSSDK.Polly" Version="3.7.202.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.201.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.20" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
    <PackageReference Include="ServiceStack.Aws" Version="6.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Japanese.Core\Japanese.Core.csproj" />
  </ItemGroup>

</Project>
