<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Kanji\Mappings\Kanjidic2Extension_Kanjidic2_Converter.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Modules\khothemegiatot.Hashify\khothemegiatot.Hashify.csproj" />
		<ProjectReference Include="..\..\Modules\khothemegiatot.WebApi\khothemegiatot.WebApi.csproj" />
		<ProjectReference Include="..\Japanese.Kanjidic2\Japanese.Kanjidic2.csproj" />
		<ProjectReference Include="..\Japanese.Repositories\Japanese.Repositories.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Dictionary\Consts\" />
		<Folder Include="Dictionary\Commands\" />
	</ItemGroup>
</Project>
