<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Kanji\Mappings\Kanjidic2Extension_Kanjidic2_Converter.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="FastCache.Cached" Version="1.8.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Japanese.CachedRepository\Japanese.CachedRepository.csproj" />
		<ProjectReference Include="..\Japanese.Kanjidic2\Japanese.Kanjidic2.csproj" />
		<ProjectReference Include="..\Japanese.Repositories\Japanese.Repositories.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Dictionary\Consts\" />
		<Folder Include="Dictionary\Mappings\" />
		<Folder Include="Dictionary\Commands\" />
		<Folder Include="Dictionary\Queries\" />
		<Folder Include="KanjiRadical\Mappings\" />
	</ItemGroup>
</Project>
