<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5b6bbcb5-d7c3-4310-9fb5-8905eb0f2ceb</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\CommonWordController.cs" />
    <Compile Remove="Controllers\HiraganaController.cs" />
    <Compile Remove="Controllers\KanjiLevelController.cs" />
    <Compile Remove="Controllers\KanjiRadicalController.cs" />
    <Compile Remove="Controllers\KanjiTypeController.cs" />
    <Compile Remove="Controllers\KatakanaController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.200.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.20" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Japanese.Services\Japanese.Services.csproj" />
  </ItemGroup>

</Project>
